spring:
  application:
    name: jounralApplication
  mongodb:
    uri: mongodb+srv://Roshan11:cr7chaudhary@noderoshan.a8gbrsg.mongodb.net/journalSpringboot?retryWrites=true&w=majority
  data:
    mongodb:
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal